### ISSUE TITLE
Todo checklist for first release 

### ISSUE THREAD

**Issue by mjakot** [mjakot/BetterBPMGD#4]
- [x] Finish BetterBPMGDCLI

  - [x] Make better flow for editing level
  - [x] Add song to LocalLevelData.cs
  - [x] Create some kind of controller
  - [x] Test that everything works
  - [x] Create command line interface
- [ ] Finish BetterBPMGD
  - [ ] Finish UI and some functionality 
  - [ ] Connect BetterBPMGD to BetterBPMGDCLI
- [ ] Release both ui and cli versions

### This list is not complete and will be extended

**Comment by mjakot** [comment]
nah bro whatever
